language: python
sudo: false
python:
    - 3.5
    - 3.4
    - 3.3
    - 2.7
sudo: false
install:
    - travis_retry pip install ipython nose coveralls
script:
    - cd /tmp && iptest ipyext --coverage xml && cd -
after_success:
    - cp /tmp/ipy_coverage.xml ./
    - cp /tmp/.coverage ./
    - coveralls
